spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/blogging_platform
      database: blogging_platform
  profiles:
    active: dev
  graphql:
    graphiql:
      enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true



